# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sampfin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 646)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 761, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.horizontalLayout.addWidget(self.l1)
        self.label1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.l2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.horizontalLayout.addWidget(self.l2)
        self.label2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.horizontalLayout.addWidget(self.label2)
        self.l3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setObjectName("l3")
        self.horizontalLayout.addWidget(self.l3)
        self.label3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.horizontalLayout.addWidget(self.label3)
        self.l4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l4.setFont(font)
        self.l4.setObjectName("l4")
        self.horizontalLayout.addWidget(self.l4)
        self.label4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.horizontalLayout.addWidget(self.label4)
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(20, 30, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.l5.setFont(font)
        self.l5.setObjectName("l5")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(30, 180, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l6.setFont(font)
        self.l6.setObjectName("l6")
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setGeometry(QtCore.QRect(190, 180, 55, 16))
        self.l7.setText("")
        self.l7.setObjectName("l7")
        self.l8 = QtWidgets.QLabel(self.centralwidget)
        self.l8.setGeometry(QtCore.QRect(480, 180, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l8.setFont(font)
        self.l8.setObjectName("l8")
        self.l9 = QtWidgets.QLabel(self.centralwidget)
        self.l9.setGeometry(QtCore.QRect(620, 180, 55, 16))
        self.l9.setText("")
        self.l9.setObjectName("l9")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 220, 281, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rb1.setFont(font)
        self.rb1.setCheckable(True)
        self.rb1.setObjectName("rb1")
        self.horizontalLayout_2.addWidget(self.rb1)
        self.rb2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rb2.setFont(font)
        self.rb2.setObjectName("rb2")
        self.horizontalLayout_2.addWidget(self.rb2)
        self.rb3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rb3.setFont(font)
        self.rb3.setObjectName("rb3")
        self.horizontalLayout_2.addWidget(self.rb3)
        self.rb4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rb4.setFont(font)
        self.rb4.setObjectName("rb4")
        self.horizontalLayout_2.addWidget(self.rb4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 270, 711, 271))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.list1 = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.list1.setObjectName("list1")
        self.horizontalLayout_4.addWidget(self.list1)
        spacerItem = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.list2 = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.list2.setObjectName("list2")
        self.horizontalLayout_4.addWidget(self.list2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(450, 210, 281, 89))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.l10 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l10.setFont(font)
        self.l10.setObjectName("l10")
        self.horizontalLayout_5.addWidget(self.l10)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.pic = QtWidgets.QLabel(self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(540, -10, 191, 71))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("grabon-cricket-fantasy.png"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.fantasylabel = QtWidgets.QLabel(self.centralwidget)
        self.fantasylabel.setGeometry(QtCore.QRect(550, 40, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.fantasylabel.setFont(font)
        self.fantasylabel.setObjectName("fantasylabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        MainWindow.setMenuBar(self.menubar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        self.actionSAVE_Team = QtWidgets.QAction(MainWindow)
        self.actionSAVE_Team.setObjectName("actionSAVE_Team")
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        self.menuManage_Teams.addAction(self.actionNEW_Team)
        self.menuManage_Teams.addAction(self.actionOPEN_Team)
        self.menuManage_Teams.addAction(self.actionSAVE_Team)
        self.menuManage_Teams.addAction(self.actionEVALUATE_Team)
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.list1.itemDoubleClicked.connect(self.excludelist1)
        self.list2.itemDoubleClicked.connect(self.excludelist2)


        self.rb1.toggled.connect(self.ctg)
        self.rb2.toggled.connect(self.ctg)
        self.rb3.toggled.connect(self.ctg)
        self.rb4.toggled.connect(self.ctg) 


        

        self.menuManage_Teams.triggered[QtWidgets.QAction].connect(self.ManageTeams)
        
        
        self.bat=0
        self.bwl=0
        self.ar=0
        self.wk=0
        self.avl=1000
        self.used=0

        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l1.setText(_translate("MainWindow", " Batsmen (BAT)"))
        self.l2.setText(_translate("MainWindow", "Bowlers (BOW)"))
        self.l3.setText(_translate("MainWindow", "All Rounders (AR)"))
        self.l4.setText(_translate("MainWindow", "Wicket-Keeper (WK)"))
        self.l5.setText(_translate("MainWindow", "Your Selections"))
        self.l6.setText(_translate("MainWindow", "Points Available"))
        self.l8.setText(_translate("MainWindow", "Points Used"))
        self.rb1.setText(_translate("MainWindow", "BAT"))
        self.rb2.setText(_translate("MainWindow", "BOW"))
        self.rb3.setText(_translate("MainWindow", "AR"))
        self.rb4.setText(_translate("MainWindow", "WK"))
        self.l10.setText(_translate("MainWindow", "Team Name"))
        self.fantasylabel.setText(_translate("MainWindow", " Internshala Fantasy Cricket"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "OPEN Team"))
        self.actionSAVE_Team.setText(_translate("MainWindow", "SAVE Team"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))


      

    def ManageTeams(self,action):
        txt=(action.text())
        if txt=='NEW Team':
            self.bat=0
            self.bwl=0
            self.ar=0
            self.wk=0
            self.avl=1000
            self.used=0
            self.list1.clear()
            self.list2.clear()
            text, ok=QtWidgets.QInputDialog.getText(MainWindow, "Team", "Enter team name:")
            if ok:
                self.lineEdit.setText(str(text))

            self.display()
        if txt=='SAVE Team':
            count=self.list2.count()
            selected=""
            for i in range(count):
                selected+=self.list2.item(i).text()
                if i<count:
                    selected+=","
            self.saveteam(self.lineEdit.text(),selected,self.used)
        if txt=='OPEN Team':
            self.bat=0
            self.bwl=0
            self.ar=0
            self.wk=0
            self.avl=1000
            self.used=0
            self.list1.clear()
            self.list2.clear()
            self.display()
            self.openteam()
        if txt=='EVALUATE Team':
            from scorecal import Ui_Dialog
            Dialog = QtWidgets.QDialog()
            ui = Ui_Dialog()
            ui.setupUi(Dialog)
            ret=Dialog.exec()
            
    def display(self):
        self.label1.setText(str(self.bat))
        self.label2.setText(str(self.bwl))
        self.label3.setText(str(self.ar))
        self.label4.setText(str(self.wk))
        self.l7.setText(str(self.avl))
        self.l9.setText(str(self.used))

    def criteria(self,ctg,item):
        msg=''
        if ctg=="BAT" and self.bat>=5:msg="You can't select more than 5 Batsmen "
        if ctg=="BWL" and self.bwl>=5:msg="You can't select more than 5 Bowlers"
        if ctg=="AR" and self.ar>=3:msg="You can't select more than 3 Allrounders"
        if ctg=="WK" and self.wk>=1:msg="You can't select more than one wicket-keeper"
        if msg!='':
            self.showdlg(msg)
            return False
        if int(self.avl)<=0:
            msg="No more points available"
            self.showdlg(msg)
            return False
        if ctg=="BAT":self.bat+=1
        if ctg=="BWL":self.bwl+=1
        if ctg=="AR":self.ar+=1
        if ctg=="WK":self.wk+=1
        sql="SELECT Value from stats where Player='"+item.text()+"'"
        MyTeam=sqlite3.connect('cricket.db')
        curteam=MyTeam.cursor()
        cur=curteam.execute(sql)
        row=cur.fetchone()
        self.avl-=int(row[0])
        self.used+=int(row[0])
        return True

    def excludelist1(self,item):
        ctg=''
        if self.rb1.isChecked()==True:ctg='BAT'
        if self.rb2.isChecked()==True:ctg='BWL'
        if self.rb3.isChecked()==True:ctg='AR'
        if self.rb4.isChecked()==True:ctg='WK'
        ret=self.criteria(ctg,item)
        
        if ret==True:
            self.list1.takeItem(self.list1.row(item))
            self.list2.addItem(item.text())
            self.display()
    def ctg(self):
        ctg=''
        if self.rb1.isChecked()==True:ctg='BAT'
        if self.rb2.isChecked()==True:ctg='BWL'
        if self.rb3.isChecked()==True:ctg='AR'
        if self.rb4.isChecked()==True:ctg='WK'

        self.enlist(ctg)

    def excludelist2(self,item):
        self.list2.takeItem(self.list2.row(item))
        MyTeam=sqlite3.connect('cricket.db')
        curteam=MyTeam.cursor()
        cur=curteam.execute("SELECT Player,Value,ctg FROM stats WHERE Player='"+item.text()+"'")
        row=cur.fetchone()
        self.avl=self.avl+int(row[1])
        self.used=int(self.used)-int(row[1])
        ctg=row[2]
        if ctg=="BAT":
            self.bat-=1
            if self.rb1.isChecked()==True:self.list1.addItem(item.text())
        if ctg=="BWL":
            self.bwl-=1
            if self.rb2.isChecked()==True:self.list1.addItem(item.text())
        if ctg=="AR":
            self.ar-=1
            if self.rb3.isChecked()==True:self.list1.addItem(item.text())
        if ctg=="WK":
            self.wk-=1
            if self.rb4.isChecked()==True:self.list1.addItem(item.text())
        self.display()


    def enlist(self,ctg):
        if self.lineEdit.text()=='':
            self.showdlg("Enter team name:")
            return
        self.list1.clear()
        sql="SELECT Player from stats where ctg='"+ctg+"';"
        MyTeam=sqlite3.connect('cricket.db')
        curteam=MyTeam.cursor()
        cur=curteam.execute(sql)
        for row in cur:
            selected=[]
            for i in range(self.list2.count()):
                selected.append(self.list2.item(i).text())
            if row[0] not in selected:self.list1.addItem(row[0])
            
    def openteam(self):
       
        sql="select Name from teams;"
        MyTeam=sqlite3.connect('cricket.db')
        curteam=MyTeam.cursor()
        cur=curteam.execute(sql)
        teams=[]
        for row in cur:
            teams.append(row[0])
        
        team, ok=QtWidgets.QInputDialog.getItem(MainWindow,"Fantasy Cricket Team","Choose A Team",teams,0,False)
        if ok and team:
            self.lineEdit.setText(team)
        
        sql1="SELECT Players,Value from teams where Name='"+team+"';"
        MyTeam=sqlite3.connect('cricket.db')
        curteam=MyTeam.cursor()
        cur=curteam.execute(sql1)
        row=cur.fetchone()
        selected=row[0].split(',')
        self.list2.addItems(selected)
        self.used=row[1]
        self.avl=1000-int(row[1])
        count=self.list2.count()

        for i in range(count-1):
            ply=self.list2.item(i).text()
            sql="select ctg from stats where Player='"+ply+"';"
            MyTeam=sqlite3.connect('cricket.db')
            curteam=MyTeam.cursor()
            cur=curteam.execute(sql)
            row=cur.fetchone()
            ctg=row[0]
            if ctg=="BAT":self.bat+=1
            if ctg=="BWL":self.bwl+=1
            if ctg=="AR":self.ar+=1
            if ctg=="WK":self.wk+=1  

        self.display()
       
    def saveteam(self,nm,ply,val):    
        if self.bat+self.bwl+self.ar+self.wk!=11:
            self.showdlg("Need 11 players")
            return
        #MyTeam=sqlite3.connect('cricket.db')
        try:
            MyTeam=sqlite3.connect('cricket.db')
            curteam=MyTeam.cursor()
            cur=curteam.execute("INSERT INTO teams (Name,Players,Value) VALUES ('"+nm+"','"+ply+"','"+str(val)+"');")
            self.showdlg("Team Saved Succesfully")
            MyTeam.commit()
        except:
            self.showdlg("Error")
            MyTeam.rollback()   
        
    def showdlg(self,msg):
        Dialog=QtWidgets.QMessageBox()
        Dialog.setText(msg)
        Dialog.setWindowTitle("Fantasy cricket Team ")
        ret=Dialog.exec()
if __name__ == "__main__":
    import sqlite3
    MyTeam = sqlite3.connect('cricket.db')
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
